- README.md
- lua/toggleterm.lua
Thanks for making this plugin. I could not find a simple way to create a popup/scratch terminal so I was about to write my own. 
This pr is adding persistent size to the terminal split. I use the popout terminal for things like compile checking my code. I find the the errors are longer then the terminal so I make it bigger to read. When I toggle it again it would change back to the size in the preference. 
Now before the split is hidden the size is saved to be later used when creating new open split.
> Persist size of terminal across toggle

- lua/toggleterm.lua
When closing terminal from outside, it will leave you in mode that
you were in terminal.
example:
- open terminal - be in insert mode inside termnal
- move back to file - mode doesnt matter
- close terminal - and it will switch to insert mode
> `stopinsert' after hiding terminal

- README.md
- lua/toggleterm.lua
- lua/toggleterm/colors.lua
This PR adds `shading_factor` to the available options so a user can tweak the amount of shading for the terminal buffer. It also darkens light backgrounds more by default.
> Add ability to tweak degree of shading

- README.md
- lua/toggleterm.lua
- plugin/toggleterm.vim
This PR adds the ability to open toggle term to a specific directory.
e.g.
```vim
:ToggleTerm size=25 dir=~/.dotfiles
```
It required a bit of a refactor so I could specify the opening directory and differentiate it from other args like size. Unfortunately the `lua`,`viml` command declaration is a bit rough atm, so the current implentation was the best workaround I could find.
Unfortunately the tradeoff is that using `:TermExec` now works like
```vim
:TermExec size=30 cmd="git status" dir=~/work-repo
```
Since distinguishing the size and dir from the command would have been tough otherwise
Fixes #4.
> Add ability to specify opening directory

- .github/workflows/test.yaml
- README.md
- lua/toggleterm.lua
- lua/toggleterm/config.lua
- lua/toggleterm/constants.lua
- lua/toggleterm/terminal.lua
- lua/toggleterm/ui.lua
- lua/toggleterm/utils.lua
- tests/minimal.vim
- tests/terminal_spec.lua
This PR refactors a lot of the ad hoc logic from this plugins implementation and encapsulates it into a `Terminal` class, it also re-organises things so that creating new layouts such as opening a `window` or `tab` are easier.
This will also pave the way to having a floating window and a terminal api that users can use via
```lua
local Terminal = require('toggleterm.terminal').Terminal
local lazy_git_term  = Terminal:new{
cmd = "lazygit",
direction = "floating",
dir = "<directory>",
}
lazy_git_term:toggle()
```
- Add floating window layout
- validate opening with dynamic layout is possible
>          Refactor: Create terminal class API

- README.md
- lua/toggleterm/config.lua
- lua/toggleterm/terminal.lua
Added an extra clause to allow another shell by simply setting vim.g.defaultShell = "myshell"
> Allow to chose custom shell

- lua/toggleterm/terminal.lua
Check if terminal is open before trying to close it in `Terminal:shutdown`.
Also allows `reset` to run without error even with closed terminals.
> Check if terminal is open in `Terminal:shutdown`

- lua/toggleterm/ui.lua
- tests/terminal_spec.lua
Allows users to give a function that returns the size wanted.
The option to simply give a number is kept.
Works for size of split and for width and height of float.
---
For example a user can give use the following in their setup:
```
⋮
size = function(term)
if term.direction == 'horizontal' then
return math.floor(vim.o.lines * 0.2)
elseif term.direction == 'vertical' then
return math.floor(vim.o.columns * 0.3)
end
end,
⋮
```
To have horizontally split terminals take up 20% of the height, and vertically split terminals take up 30% of the width.
> Add option to give a function for the size

- README.md
- lua/toggleterm/terminal.lua
Currently when opening a new terminal and providing a command, this command is formatted using semicolons, ";".
- On Linux, this can be used as a separator between any list of commands (I think?).
- On Windows, some commands can be separated with semicolons, but others can't.
Some commands will read the entire line, and not stop at semicolons (see [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/----command-separator-#remarks)).
(In my use case, the "vifm" command line file manager reads the full line.)
Therefore it would be good to add an option to disable this formatting.
> Format cmd in OS compatible way

- lua/toggleterm/terminal.lua
This should fix #43 by deleting the buffer when the process exits
> fix: delete buffer on process exit

- README.md
- lua/toggleterm.lua
- plugin/toggleterm.vim
- tests/terminal_spec.lua
This PR adds the ability to open all terminals (that were previously opened) or close all currently opened terminals.
Fixes #48
> feat: add ToggleTerm{Open|Close}All commands

- lua/toggleterm/commandline.lua
Hey, after a while without using my `TermExec` commands I decided to trigger them and found that they weren't working properly since the command was `null` instead of the passed value (e.g. `git status`) when double quotes are used for enclosing the command. This PR aims to fix this behavior by checking two things before matching the command with the quoting.
1. Checks if the current OS is Windows or not by using `jit.os`.
2. Checks if the `+shellslash` feature exists and if it is turned on.
But, why check those things? Well, they're needed for some reasons:
1. The Vimscript `shellescape` function works in a very peculiar way regarding the quoting.
**From the** `shellescape` function **docs:**
> On Windows when `'shellslash'` is not set, encloses {string} in double-quotes and doubles all …
> fix(parse): correct quotes matching for TermExec commands

- README.md
- lua/toggleterm.lua
`<Cmd>` is more flexible and slightly shorter.
> Use <Cmd> instead of :<c-u> in mappings

- lua/toggleterm/terminal.lua
Ran into a problem where each newly opened terminal would have an incremental id 
assigned to it, even after all previous ones have been closed. These changes fixed 
things for me, so I'm making a pr instead of raising an issue, as requested.
> fix: remove id from the list of available ids on terminal exit

- lua/toggleterm.lua
- lua/toggleterm/terminal.lua
Expand user-provided `dir` at the start of `Terminal:open`.
This then matches the setup for `require('toggleterm').exec`
> feat: expand `self.dir` before opening a `Terminal`

- README.md
- lua/toggleterm/terminal.lua
I didn't notice this in #53.
This change actually solves a bug: when mapping is `<C-t>` and it is mapped to `<C-\><C-n>:execute v:count . "ToggleTerm"<CR>`, pressing `<C-\><C-t>` types `<C-n>:execute v:count . "ToggleTerm"<CR>` in the terminal, and changing `<C-\><C-n>:` to `<Cmd>` solves this bug.
> Use <Cmd> instead of <C-\><C-N>: in terminal mode mapping

- README.md
- lua/toggleterm/terminal.lua
Add a `close_on_exit` field to the Terminal class.
If not specified it uses the global `close_on_exit` specified in the config.
> feat: add close_on_exit field to the Terminal class

- README.md
Clarify the use of the open_mapping key in relation to insert and terminal modes
> docs: add warning about using a count in terminal mode

- lua/toggleterm/terminal.lua
When using a floating terminal, opening and closing under certain scenarios results in a shift in the buffer's contents to the left.
To reproduce open a terminal with "float" direction, run `lazygit` and toggle the term a couple of times. The terminal's content will shift.
The problem may be an issue with using `startinsert!` as an autocmd, refactoring it to be executed once the terminal is open as a regular conditional fixes the issue.
If the root cause of the problem is related to other things let me know, but I believe this solution shouldn't sacrifice performance or code consistency.
> refactor: remove bang from startinsert command

- lua/toggleterm/terminal.lua
Windows system has two shell, Cmd and PowerShell (pwsh). 
Cmd can uses :: to comment, and  & to split. 
Powershell uses the # to comment, and ; to split, similar as bash. 
Toggleterm now distinguishes between linux and windows , but not deal with the cmd and powershell under the windows environment, resulting in the following error when using powershell:
This PR distinguishes the difference between cmd and powershell in windows environment to use the correct separator in powershell.
> feat: support both cmd and powershell(pwsh) for windows

- lua/toggleterm/terminal.lua
Should fix #110, by replacing \n with \r\n for cmd or \r for powershell. Make sure that `set shellslash` is executed on startup or `null` will still be sent to the terminal. Tested and working on Windows 11 with shell set as Windows' internal versions of cmd.exe and powershell.exe, and Powershell Core (pwsh.exe). I also verified in WSL that this doesn't break any Linux functionality.
> fix: use proper newline characters on windows

- plugin/toggleterm.vim
Explicitly state compatible versions of neovim in error message.
> fix: update error message to explicitly state compatible versions

- README.md
- doc/toggleterm.txt
- lua/toggleterm/terminal.lua
- lua/toggleterm/ui.lua
Previously it was necessary to always create a new custom Terminal instance to attach `on_stdout()` and `on_stderr()` functions. With this PR these functions can be configured globally and thus serve as a default for *all* terminals.
A wrapper will add the corresponding terminal as the first parameter to `on_stdout()` and `on_stderr()` to be consistent with how on_exit() is called (dot operator vs colon operator). This is technically a breaking change, but since the documentation for `on_exit()` has been wrong all this time without anyone complaining I don't know if this would have any real impact on the wider userbase.
It also no longer tries to switch the terminal window just see if it is open or not. `win_gettype()` will return an empty string for normal windows, or "unknown" if the …
> feat!: allow global config of on_exit(), on_stdout(), on_stderr()

- lua/toggleterm/terminal.lua
When using `5ToggleTerm`, but there is no terminal with id=5, a new terminal was created, *but not with id=5*. Instead a new terminal was created by calling `next_id()`, creating the weird behavior where `5ToggleTerm` would create new terminals until `next_id()` would finally return 5.
This PR fixes this by creating a new terminal with the specified ID when such a terminal does not already exist.
fixes #146
> fix: create terminal with called ID if not found

- lua/toggleterm/terminal.lua
A bug was introduced in #162 that causes floating terminal windows to not close as expected when toggling, due to the change in the `Terminal:is_open` method:
```diff
-  --- TODO: try open will actually attempt to switch to this window
-   local win_open = ui.try_open(self.window)
+   -- empty string corresponds to a normal window
+   local win_open = fn.win_gettype(self.window) == ""
```
You can observe the issue when configuring a terminal toggle with a `"float"` direction. This fix includes an additional check on the window type to handle floating (`"popup"`) window types.
> fix: toggle floating windows properly

- lua/toggleterm/terminal.lua
Fix newline_chr,command_sep,comment_sep to be set correctly even if vim.o.shell and the specified shell are different on windows.
> fix: use specified shell on windows

- README.md
- lua/asd.lua
- lua/toggleterm.lua
- plugin/toggleterm.vim
#172 
Purpose of the PR is to make "sending lines" from a file to the toggled terminal available for the user (as simple as possible). Can come handy in multiple situations (e.g. executing code with `ipython`)
The PR contains:
- Sending a single line where our cursor is `:ToggleTermSendCurrentLine <T_ID>`
- Sending the lines from a visual selection `:ToggleTermSendVisualLines <T_ID>`
- Sending the visual selection (e.g. block of code, single word) `:ToggleTermSendVisualSelection <T_ID>`
(`<T_ID>` is an optional argument. It's the ID of the terminal where we want to send the line(s) )
Example
> feat: send line(s) to the terminal

- lua/toggleterm/terminal.lua
Solves the problem pointed in https://github.com/akinsho/toggleterm.nvim/pull/182#issuecomment-1086192923
Since command_sep and comment_sep are used to invoke the shell for toggleterm, it is correct to use `vim.o.shell`.
newline_chr is sent to the shell for toggleterm that has been started, so it is correct to use the specified shell.
> fix: separator on windows with powershell

- lua/toggleterm.lua
Thanks for this awesome plugin first! This PR tries to fix the bug of the cursor jumping back problem since the function `nvim_win_set_cursor` simply sets the cursor position on that window without jumping back to it.
> fix(send_lines): place cursor back in the original window

- lua/toggleterm.lua
- lua/toggleterm/ui.lua
This PR fixes #203 which is caused by terminals not known to toggleterm being highlighted but not being of type `Terminal` so missing the methods and variables that were expected. I've added defaults within that function but it might be worth being able to represent unknown terminals at some point
> fix(ui): handle highlighting unknown terminals

- README.md
The 'window' was deprecated in favor of 'tab'
> docs(README): rename 'window' direction option to 'tab'

- README.md
- lua/toggleterm/terminal.lua
- lua/toggleterm/ui.lua
I was trying to spawn multiple terminal jobs in the background, but it seems that without `task:open()` the jobs won't be started. It is possible to do `task:open(); task:close()`, at least with `direction='float'`, but doing this for multiple terminals at once seems wrong.
This PR adds `task:spawn()` which only creates terminal buffer with the job, without opening a window yet. The window can be opened later and it doesn't seem to cause any problems. Using `nvim_buf_call` it was possible to make the `termopen` call actually use the background buffer instead of the current one.
> feat: add api to spawn tasks without opening a window

- README.md
- lua/toggleterm/terminal.lua
- tests/terminal_spec.lua
This allows to pass environmental variables to terminal jobs. 
While adding `env` test I also included an unrelated test for the new `term:spawn()` (can move it to separate PR if that's a problem).
> Option to pass env/clear_env to jobstart

- lua/toggleterm/colors.lua
Thanks for this awesome plugin first!
Sometimes `shade_color()` returns invalid color and fails to darken window.
For example, my colorsheme is [terafox](https://github.com/EdenEast/nightfox.nvim) and its background color is `'#152528'`.
In this case `shade_color('#152528', -30)` returns `'#e191c'` (not `'#0e191c'`).
Zero padding fixes this problem.
> fix: shade_color

- lua/toggleterm/terminal.lua
Add delete call in the shutdown method for terminal, this will allow the terminal to properly be cleaned up when shutdown. Shutdown is used when
one desires to kill the terminal and not simply close it but rather
completely destroy it and free up a slot for another term instance.
> feat(terms): delete internal term resources on shutdown.

- lua/toggleterm/terminal.lua
- tests/terminal_spec.lua
Simplified next_id() by removing the 'ids' table and calling
get_all() instead. The previous implementation did not always
produce unique IDs.
Remodelled the next_id test case by creating actuall terminals.
Before this patch, if you created 3 terminals with ID 1, 2, 3
and then closed the first terminal with id 1 using "exit",
the next_id was calculated to 2, resulting in a duplicate ID.
> fix(next_id): Terminal IDs should be unique.

- README.md
- doc/toggleterm.txt
- lua/toggleterm.lua
- lua/toggleterm/config.lua
- lua/toggleterm/terminal.lua
- tests/state_spec.lua
This PR allows each terminal to keep track of the mode the user was last in and return to in when they re-open the terminal. Fixes #76
@kdheepak can you give this a try? it should keep track of the terminal state and re-use whatever it last was
> feat: persist terminal mode

- README.md
The current installation instructions yield a syntax error. Fixed `vim-plug` installation line to match the examples in the [vim-plug docs](https://github.com/junegunn/vim-plug).
> docs(README): update `vim-plug` installation instructions

- lua/toggleterm/terminal.lua
When a terminal is opened an `autocmd` is attached to the given terminal buffer to delete the terminal from the in-memory register. This becomes a problem when multiple terminals are opened as previously created auto commands are replaced by subsequent creations, meaning only the last terminals reference will be removed when it is closed, all others will remain.
Rather than relying on multiple `autocmd`s which have closure over the terminals they need to close, this PR uses a single command which uses the buffer number from the callback to locate the terminal which needs to be deleted. My neovim/lua knowledge isn't the best so feel free to edit if you have a better solution.
My motivation for wanting this behaviour is that I use sessions to switch between projects. If I have multiple …
> fix: Ensure terminals are deleted correctly when multiple open

- lua/toggleterm/ui.lua
running `:toggleterm` when terminal is only opened tab results in
```Error executing Lua callback: .../pack/packer/start/toggleterm.nvim/lua/toggleterm/ui.lua:317: Vim(tabclose):E784: Cannot close last tab page
stack traceback:
[C]: in function 'cmd'
.../pack/packer/start/toggleterm.nvim/lua/toggleterm/ui.lua:317: in function 'close_tab'
.../pack/packer/start/toggleterm.nvim/lua/toggleterm/ui.lua:361: in function 'close'
...packer/start/toggleterm.nvim/lua/toggleterm/terminal.lua:253: in function 'close'
...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:82: in function 'smart_toggle'
...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:342: in function 'toggle'
...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:315: in function 'toggle_command' …
```
> fix: don't try to close the last tab

- lua/toggleterm/terminal.lua
The value of go_back has been inverted on check. This caused the terminal to close when set to **false**
> fix(terminal): keep focus in current on TermExec in 'float' orientation

- lua/toggleterm.lua
This is so [fzf-lua](https://github.com/ibhagwan/fzf-lua)'s selection menu can properly override the prompt suffix.
https://github.com/ibhagwan/fzf-lua/blob/0944e1e/lua/fzf-lua/providers/ui_select.lua#L90
```lua
['--prompt']          = prompt:gsub(":%s?$", "> "),
```
> style: add colon to terminal selection prompt

- doc/toggleterm.txt
- lua/toggleterm.lua
- lua/toggleterm/terminal.lua
- lua/toggleterm/ui.lua
When seeing if the terminal is toggled open, but only check current win for the current terminals windows when finding windows to see if any terminals are open.
> fix(ui): check all tabs for current terminal's window

- README.md
"Closing terminal" is not a valid cmd command.
> docs(README): change cmd on closing the terminal in example

- lua/toggleterm.lua
This property can be used in Neovim 0.7 and above. Useful for plugins like which-key.nvim
> feat: add desc property to key mappings

- lua/toggleterm.lua
Otherwise all autocmds won't be applied if one uses `cmd` as the shell on Windows
> fix: include double colon pattern for autocmds on Windows

- lua/toggleterm/ui.lua
Modified `toggleterm/ui.lu` to allow that `row` and `col` in options can be given as function. To use
```
vim.F.if_nil(M._resolve_size(opts.row, term), default_value)
``` 
form, for readability sake, default values are calculated first. While this added unnecessary calculation I thought overhead is neglectable.  Also modified how `width` and `height` are calculated, to reflect same approach.
> feat: "row" and "col" can be given as function (#343)

- README.md
I thinks this comment describes what the key is for better, the other comment was misleading. This comment also has the correct default value.
> docs(README): change comment for `shading_factor` key in setup

- lua/toggleterm/terminal.lua
Currently the `on_create` callback is not being called when creating a task using `Terminal:spawn()` instead of `Terminal:open()`.
> fix: add missing self:on_create() to Terminal:spawn()

- README.md
I think that this PR would avoid problems like those:
[Here](https://vi.stackexchange.com/questions/39967/cannot-open-terminal-ini-nvim/39968?noredirect=1#comment73213_39968)'s the vim question.
> doc(README): fix vim plug installation instructions

- README.md
- doc/toggleterm.txt
- lua/toggleterm.lua
- lua/toggleterm/terminal.lua
- tests/terminal_spec.lua
I find myself often wanting to open last used (toggled) terminal with the open mapping, as it feels natural to continue where you left off. Right now the first toggled terminal will be opened instead, which usually makes me re-think where I left and then I have to toggle that specific terminal that I've used.
This PR adds logic to `smart_toggle` to open last toggled terminal if none are opened, instaed of openning the first one. The changes are minimal, and I feel it doesn't complicate the code much. @akinsho  let me know what you think :)
> feat: open last toggled term on smart toggle

- README.md
- doc/toggleterm.txt
- lua/toggleterm.lua
- lua/toggleterm/terminal.lua
- lua/toggleterm/ui.lua
- tests/terminal_spec.lua
A continuation of #397 where the idea is taken a bit further, and a complete terminal view is being toggled instead of just the last toggled terminal. When working with the terminals you often want to save your complete view that you've been working on, instead of just closing terminals one by one, and opening them up (again) one by one. There's already a utility mapping that let's you open and close all of your terminals, but this doesn't take into consideration what was previously opened. Therefore to make `smart_toggle` even smarter we could save the current terminal view, and then open it up the next time it is triggered.
In order to achieve this functionality we could keep a list of terminals that were closed, and use it to go over the list to open them on next smart toggle.
> feat: restore terminal view on smart toggle

- README.md
With the terminal being in `TERM (INSERT)` mode by default, I sometimes get stuck trying to switch away from it. When I leave it open, I often use `Ctrl-w {w/h/j/k/l}` to jump in and out of it, as between other windows. It's however not as functionally or visually apparent that I'm stuck in `TERM` mode when this fails (the term cursor remaining a block may play a role).
This change switches to `Ctrl-w` in `TERM` mode and awaits the direction key. I think it complements the existing bindings well, for a more natural experience.
> docs(README): add example mapping for wincmd

- README.md
Just a quick fix as per stated in https://github.com/folke/lazy.nvim/blob/8077428e63feb0f3bf795d53b23ba1695b28ab0e/README.md?plain=1#L693
> docs(README): fix arg typos in the lazy installation example

- README.md
- doc/toggleterm.txt
- lua/toggleterm/ui.lua
When using toggleterm and [incline](https://github.com/b0o/incline.nvim) together, this change allows the user to give toggleterm a higher zindex than incline to prevent undesired overlapping.
> feat: support z-index option for floating windows

- README.md
- lua/toggleterm.lua
- lua/toggleterm/terminal.lua
- tests/terminal_spec.lua
This PR adds a `TerminalSelect` command which uses `vim.ui.select` to allow the user to choose which terminal to open or focus
> feat: add a terminal select command

- lua/toggleterm/terminal.lua
The current implementation will move focus to the terminal window when changing its directory. It would be nice to be able to do that in the background.
> feat: Allow changing terminal dir in background

- lua/toggleterm/terminal.lua
- lua/toggleterm/ui.lua
- lua/toggleterm/utils.lua
I recently discovered [stickybuf.nvim](https://github.com/stevearc/stickybuf.nvim), and it's great at preventing buffers from opening inside plugin windows, ToggleTerm included.
However, due to the way ToggleTerm sets its window options, if I accidentally/intentionally open a new file while in the ToggleTerm buffer, the new buffer inherits ToggleTerm's window options (specifically `winhighlight`, `nonumber` and `norelativenumber` for my config). This means that when stickybuf moves that buffer to a different window, it keeps those window options and thus has a dark background and no line numbers. The same kind of thing also happens without stickybuf, but opening buffers inside ToggleTerm's window causes some other glitchy behaviour if you immediately then try and open ToggleTerm using the …
> fix: replace vim.wo with nvim_set_option_value

- README.md
I spent a long time trying to understand how to do this because when I read the docs I though the `cmd` argument was required. Perhaps this is me being silly, so feel free to ignore if so, but I wanted to make the README explicit.
> Note custom terminals with no cmd option

- lua/toggleterm/terminal.lua
Refactors the `open` function to re-use spawn rather than essentially re-implement it.
> refactor(terminal): re-use spawn function

- lua/toggleterm/terminal.lua
fixes(#466)
This minor change personally resolves the issue I was facing, although potentially there might be other instances in the code where the shell option is assumed to be a string, I have not looked through the codebase for other occurrences though.
> fix: TermExec cmd with config.shell = function

- lua/toggleterm/terminal.lua
This PR sets IDs at spawn-time for terminals that were created without an id/count specifies. See linked issue for more info.
closes #487
> fix: determine custom terminal ids on spawn

- lua/toggleterm/terminal.lua
Very generic way of finding a terminal that should be adaptable to most use cases. I'm using it for finding a terminal by bufnr.
> feat: add `Terminal.find` function

- lua/toggleterm/terminal.lua
Instead of assigning custom terminals' IDs on spawn, this just ensures that a different terminal does not exist with the same ID. Toggling normal terminals still works, but on spawn / resurrect, if there is a collision the terminal will be given the next available ID. This ensures that no terminals will be overwritten from the list, which previously could happen if a terminal wasn't spawned immediately on creation, or if an "orphaned" terminal was resurrected.
> fix(#487): avoid terminal id collisions in __add

- README.md
- lua/toggleterm.lua
- lua/toggleterm/commandline.lua
- lua/toggleterm/terminal.lua
- tests/command-complete_spec.lua
- tests/commandline_spec.lua
Adding the `name` param to `:ToggleTerm` and `:TermExec` commands to allow setting the `display_name` for the terminal while creating it.
Implements the feature I'd suggested [here](https://github.com/akinsho/toggleterm.nvim/issues/332#issuecomment-1679505869).
Let me know your thoughts. Thanks!
> feat: add name param to ToggleTerm and TermExec

- lua/toggleterm/terminal.lua
functionality added to clear an already opened terminal in windows.
clear function is not valid on windows os. Therefore added additional check for os.
> clear terminal on windows

- README.md
Adds the missing ')' after 'end' on the first example for setting up keymap for send_lines_to_terminal.
> docs: add missing ')' after end in TermSelect keymaps example

- doc/toggleterm.txt
- lua/toggleterm/terminal.lua
R on cmd.exe on windows adds an extra newline using the current logic (newline is chosen as: "\r\n"). This proposal makes `newline_chr` a property of the `Terminal`, and allows the user to specify it's value when creating custom terminals.
> newline_chr is optionally user-specified

- README.md
- doc/toggleterm.txt
- lua/toggleterm/config.lua
- lua/toggleterm/ui.lua
Got an idea from #504 PR
- title is enabled when `display_name` is provided
- will not fail on NeoVim versions prior to 0.9
- added documentation entries
- `title_pos` is under more appropriate  `float_opts` section
> feat: enabling title for floating terminals

- README.md
- doc/toggleterm.txt
**UPDATE:**
A doc-only change to describe that `row` and `col` are also configurable via number or function, like `width` and `height`.
-----
**Original description:**
~This one-line patch allows me to do something like this:~
```
vim.g.toggle_quake_float = true
```
~in my `init.lua`. Then by setting~
```
float_opts = {
height = math.floor(vim.o.lines * 0.4),
width = vim.o.columns,
}
```
~I get a true Quake-style float terminal.~
~It didn't seem worthwhile to create an entirely new `direction` when it's such a tiny variation on the existing `float`, but there might be an argument to make it part of the `float_opts` table?~
~If you think this change is worth incorporating, I can add the corresponding paragraph to `toggleterm.txt`.~
> doc(float_opts): add number/function description of row and col

- lua/toggleterm.lua
This pull request simply adds `id` to the arguments passed to `M.exec()` when `trim_spaces = false` in `toggleterm.send_lines_to_terminal`.
This wasn't causing issues for the various user commands (e.g., `ToggleTermSendCurrentLine`) because they all set `trim_spaces = true`. 
It was causing issues for implementations that call `send_lines_to_terminal` with `trim_spaces = true` that tried sending text to terminals other than the first terminal, where `term.id != 1`; Text was always sent to the first terminal.
> Bugfix: toggleterm.send_lines_to_terminal wasn't passing id to M.exec() when trim_spaces = false

- lua/toggleterm/terminal.lua
As [reedline stating in their doc](https://github.com/nushell/reedline/tree/d2e0d320a9258b632c4470cc9d7637d1f132916a/src#technical-background), nushell uses the same CRLF policy like Windows. This PR adds the support for it.
> Correct CR for Nushell

- lua/toggleterm.lua
As `on_choice()` actions depend on modifying terminal objects in place, make sure to operate on exact element and not a copy. As users can override `vim.ui.select()`, its implementation might return an item's copy (which is not explicitly prohibited) making later `on_choice()` actions not 100% full proof.
> fix: ensure `on_choice` operates on exact `items` element

- README.md
This PR add missing `display_name` argument to documentation.
> doc: add missing display_name argument

- lua/toggleterm.lua
nvim_win_set_cursor indexes rows from 1 but columns from 0, while we seem to index columns from 1 as well.
Fixes #542
> Fix cursor position after motion

- lua/toggleterm/terminal.lua
Currently, autochdir won't work for custom terminals.
So currently I encounter scenarios like the following: Opening a custom terminal with i.e lazygit in a git project then closing the terminal, switching buffers to another git project and re toggling it, keeps opening lazygit in the first directory.
The changes in the PR aim to make this functionality work - switching buffers in the same session to another git project and opening a custom terminal should open it with the new git projects working directory.
> fix: autochdir for custom terminals

- README.md
- doc/toggleterm.txt
- lua/toggleterm.lua
- lua/toggleterm/config.lua
- lua/toggleterm/terminal.lua
- lua/toggleterm/utils.lua
I sometime use a Japanese keyboard, and it don't have the `\` key, instead it have a `¥` key.
It would be helpful for people like me who what to bind multiple keys for toggle terminal. So I modified the `open_mapping` setting to also take an array of string as parameter.
> Add string array support to `open_mapping` setting.

- README.md
- lua/toggleterm/config.lua
- lua/toggleterm/constants.lua
Fixes #579. 
Added a `shading_ratio` option that defaults to `-3`.
The bright background shading factor becomes `config.shading_ratio * config.shading_factor` after this change.
No breaking change is introduced by this pr.
> Add shading_ratio option

- lua/toggleterm/terminal.lua
I'm using quick-access shortcuts to switch to a given terminal:
```
{ "<M-&>", "<cmd>1 ToggleTerm<cr>", mode = { "n", "t" }, desc = "Toggle terminal 1" },
{ "<M-é>", "<cmd>2 ToggleTerm<cr>", mode = { "n", "t" }, desc = "Toggle terminal 2" },
{ '<M-">', "<cmd>3 ToggleTerm<cr>", mode = { "n", "t" }, desc = "Toggle terminal 3" },
{ "<M-'>", "<cmd>4 ToggleTerm<cr>", mode = { "n", "t" }, desc = "Toggle terminal 4" },
{ "<M-(>", "<cmd>5 ToggleTerm<cr>", mode = { "n", "t" }, desc = "Toggle terminal 5" },
{ "<M-->", "<cmd>6 ToggleTerm<cr>", mode = { "n", "t" }, desc = "Toggle terminal 6" },
{ "<M-è>", "<cmd>7 ToggleTerm<cr>", mode = { "n", "t" }, desc = "Toggle terminal 7" },
{ "<M-_>", "<cmd>8 ToggleTerm<cr>", mode = { "n", "t" }, desc = "Toggle terminal 8" },
{ "<M-ç>", "<cmd>9 ToggleTerm<cr>", …
```
> fix: set_mode may not be taken into account

- README.md
- lua/toggleterm/config.lua
- lua/toggleterm/ui.lua
- stylua.toml
When using Neovim with toggleterm in a vertical monitor there is not enough space to see the output of 2 or more terminals that are showed at the same time properly due to the amount of space left in it. Like in the following image
It would be better to have them stacked on top of each other so that the user can see clearly the output of each of them when using vertical monitor, or just a window with smaller width. Like in the following image
#closes https://github.com/akinsho/toggleterm.nvim/issues/616
This PR solves the problem by adding a configuration setting that can be used to be define at which point the user would like to start stacking terminals on top of each other, instead of creating them next to each other when wanting to visualize more than one at the same time. The behavior …
> Add Responsive Capabilities for horizontal direction

- lua/toggleterm.lua
Fixes #435
I spawn a terminal at startup to improve initial performance. But if I run `colorscheme` before the terminal is shown, i.e. before it's attached to a window, an error is thrown because `term.window` is nil. I have fixed to verify `term.window` is not nil.
> fix: colorscheme on hidden terminal
