lua/toggleterm.lua
When you open a term it will save a current window. When closing it will
go back to that window if possible.
Also checks if you are in different window when closing term - so your
cursor is not jumping around.
Actual behaviour is that if you open term leaving it open and jump around windows - on close term your cursor jumps to nearest window.
=> Remember origin window to come back after close

lua/toggleterm.lua
closes https://github.com/akinsho/nvim-toggleterm.lua/issues/15
=> Add "insert_mappings" option to disable creating imaps

README.md
Fix nvim_win_open <-> nvim_open_win typo
=> docs: fix README nvim_open_win help page

README.md
=> docs: open multiple terminals side-by-side

README.md, doc/toggleterm.txt, lua/toggleterm.lua, plugin/toggleterm.vim
This is useful i think for toggling terminals with just one mapping.
=> feat: add single toggle all command

lua/toggleterm.lua, plugin/toggleterm.vim
See https://github.com/akinsho/toggleterm.nvim/commit/de9a2ef88e18e109744b94ea230bcc26c7232ffa
=> feat: Force close terminals via ToggleTermToggleAll

README.md, lua/toggleterm/terminal.lua
=> feat: pass on_open option from setup

README.md, lua/toggleterm/terminal.lua
=> feat: pass on_close option from setup

lua/toggleterm/terminal.lua, lua/toggleterm/ui.lua
=> feat: dynamic resize float terms

lua/toggleterm/config.lua, tests/terminal_spec.lua
@eeeXun can you test this out and see if it fixes the issue for you
fixes #196
=> fix(config): config.highlights should respect prefs

README.md, doc/toggleterm.txt, lua/toggleterm.lua, lua/toggleterm/colors.lua, lua/toggleterm/config.lua, lua/toggleterm/terminal.lua, lua/toggleterm/ui.lua, tests/terminal_spec.lua
Also fix the issue of user highlights never being actually taken into account, and update the users highlights when the colorscheme changes.
fixes #230 #223 
@paulo-santana @Liverm0r can you both please test this PR
=> fix(colors): apply terminal highlights more consistently

lua/toggleterm.lua
Update the ToggleTermSendVisualSelection command by changing the "visual_selection" logic in M.send_lines_to_terminal in lua/toggleterm.lua.
For selection_type == "visual_selection", the lines now come from the new local function get_visual_selection which gets the lines based on the visual mode used to make the selection.
=> feat: update send visual selection

.github/workflows/test.yaml, .luarc.json, README.md, doc/toggleterm.txt, lua/toggleterm.lua, lua/toggleterm/commandline.lua, lua/toggleterm/config.lua, lua/toggleterm/terminal.lua, lua/toggleterm/ui.lua, tests/terminal_spec.lua
This is currently blocked by a weird bug where the `winhighlight` for the `WinBar` does not get applied correctly. Possibly due to https://github.com/neovim/neovim/issues/18628
=> feat(toggleterm): add a simple winbar to show terminal data

README.md, doc/toggleterm.txt
=> doc: float terminal accepts a function for size

README.md, lua/toggleterm/config.lua, lua/toggleterm/terminal.lua, lua/toggleterm/ui.lua
https://github.com/akinsho/toggleterm.nvim/issues/143
Adds the **default** behavior of auto-scrolling down on output. Can be opted-out using the `auto_scroll` config option.
=> feat: enable auto-scroll on stdout/stderr

lua/toggleterm/terminal.lua
Hi, first thanks for your awesome plugin!
I came across #307 today and I think this change fixes the issue (at least for my use case it does).
=> fix(terminal): fix scroll_bottom (#307)

README.md, lua/toggleterm/config.lua, lua/toggleterm/terminal.lua, tests/terminal_spec.lua
This enables determining the default shell dynamically. Please let me know if you are ok with such a change. If so, I will update the documentation.
=> feat(config): allow `shell` parameter to be a function

lua/toggleterm/terminal.lua
=> cmd is optional in Terminal:new()

lua/toggleterm.lua
=> fix(#496): call ToggleTermSetName with count

lua/toggleterm/commandline.lua
that is all the changes you requested
=> cmd and path now work with paths containing spaces

README.md, lua/toggleterm/config.lua, lua/toggleterm/terminal.lua
=> feat: add clear_env option
